name: 'DGC CI Reporter'
description: 'Parse unit test and coverage output and display results as check and in PR thread.'
inputs:
  language:
    description: "Choose language. Currently supported: 'python', 'javascript'."
    required: true
  github-token:
    description: "Github API token."
    required: true
  badge:
    description: "Create badge."
    default: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: python3 -m pip -r "${{ github.action_path }}/requirements.txt" && python3 -m pip install pytest coverage
      shell: bash
      if: ${{ inputs.language == 'python' }}
    - run: coverage run -m pytest --junitxml junit.xml || true && coverage report -m > coverage.txt
      shell: bash
      if: ${{ inputs.language == 'python' }}
    - run: PYTHONPATH="${{ github.action_path }}" python3 -m action.action_main ${{ inputs.language }} ${{ inputs.github-token }}
      if: ${{ inputs.language == 'python' }}
      shell: bash