name: 'DGC CI Reporter'
description: 'Parse unit test and coverage output and display results as check and in PR thread.'
inputs:
  language:
    description: "Choose language. Currently supported: 'python', 'javascript'."
    required: true
  github-token:
    description: "Github API token. Defaults to '${{ secrets.GITHUB_TOKEN }}'"
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: "composite"
  steps:
    - run: python3 -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - run: PYTHONPATH="${{ github.action_path }}" python3 -m action/action_main ${{ inputs.language }} ${{ inputs.github-token }}
      shell: bash