# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: "Install action requirements."
        run: python3 -m pip install -r ${{ github.action_path }}/requirements.txt
        shell: bash
      - uses: cyberscan/ci-action@master
        with:
          language: python
          badge: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
