# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Install requirements."
        run: python3 -m pip install -r requirements.txt
        shell: bash
      - name: "Install linter requirements."
        run: python3 -m pip install flake8 black
        shell: bash
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true
      - uses: cyberscan/ci-action@master
        with:
          language: python
          github-token: ${{ secrets.GITHUB_TOKEN }}
