name: MASTER
on:
  # run this workflow on master push
  push:
    branches: [ master ]
  # or on demand
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      # setup dependency cache
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # install repo dependencies
      - name: "Install dependencies."
        run: python3 -m pip install -r requirements.txt
        shell: bash
      # install linter dependencies
      - name: "Install linters."
        run: python3 -m pip install flake8 black
        shell: bash
      # run linters
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true
      # run tests
      - name: Run tests
        uses: cyberscan/ci-action@master
        with:
          language: python
          github-token: ${{ secrets.GITHUB_TOKEN }}
          badge: ${{ true }}
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
